databases:
  - name: estate_db
    plan: free
    databaseName: estatedb
    user: config

services:
  - type: web
    plan: free
    name: estate_server
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: db_url
        fromDatabase:
          name: estate_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: URL
        value: False
      - key: PROPERTY_KEY
        value: False
      