databases:
  - name: weather_db
    plan: free
    databaseName: weatherdb
    user: config

services:
  - type: web
    plan: free
    name: weather_server
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: db_url
        fromDatabase:
          name: weather_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: URL
        value: False
      - key: WEATHER_KEY
        value: False
      