# Generated by Django 5.1.3 on 2024-11-28 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_property_property_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='property_id',
        ),
        migrations.AddField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
    ]
